/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __THREADHIST_BPF_SKEL_H__
#define __THREADHIST_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct threadhist_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *call_count;
	} maps;
	struct {
		struct bpf_program *cuda__retprobe;
	} progs;
	struct {
		struct bpf_link *cuda__retprobe;
	} links;

#ifdef __cplusplus
	static inline struct threadhist_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct threadhist_bpf *open_and_load();
	static inline int load(struct threadhist_bpf *skel);
	static inline int attach(struct threadhist_bpf *skel);
	static inline void detach(struct threadhist_bpf *skel);
	static inline void destroy(struct threadhist_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
threadhist_bpf__destroy(struct threadhist_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
threadhist_bpf__create_skeleton(struct threadhist_bpf *obj);

static inline struct threadhist_bpf *
threadhist_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct threadhist_bpf *obj;
	int err;

	obj = (struct threadhist_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = threadhist_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	threadhist_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct threadhist_bpf *
threadhist_bpf__open(void)
{
	return threadhist_bpf__open_opts(NULL);
}

static inline int
threadhist_bpf__load(struct threadhist_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct threadhist_bpf *
threadhist_bpf__open_and_load(void)
{
	struct threadhist_bpf *obj;
	int err;

	obj = threadhist_bpf__open();
	if (!obj)
		return NULL;
	err = threadhist_bpf__load(obj);
	if (err) {
		threadhist_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
threadhist_bpf__attach(struct threadhist_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
threadhist_bpf__detach(struct threadhist_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *threadhist_bpf__elf_bytes(size_t *sz);

static inline int
threadhist_bpf__create_skeleton(struct threadhist_bpf *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "threadhist_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = 24;
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt,
			sizeof(*s->maps) > 24 ? sizeof(*s->maps) : 24);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	map = (struct bpf_map_skeleton *)((char *)s->maps + 0 * s->map_skel_sz);
	map->name = "call_count";
	map->map = &obj->maps.call_count;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "cuda__retprobe";
	s->progs[0].prog = &obj->progs.cuda__retprobe;
	s->progs[0].link = &obj->links.cuda__retprobe;

	s->data = threadhist_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *threadhist_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x07\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x09\0\x01\
\0\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x6b\x72\x65\
\x74\x70\x72\x6f\x62\x65\x2f\x5f\x5a\x39\x72\x6f\x70\x65\x5f\x6e\x6f\x72\x6d\
\x49\x4c\x62\x31\x45\x4c\x62\x30\x45\x66\x36\x5f\x5f\x68\x61\x6c\x66\x45\x76\
\x50\x4b\x54\x31\x5f\x50\x54\x32\x5f\x69\x69\x69\x69\x69\x50\x4b\x69\x66\x66\
\x66\x31\x34\x72\x6f\x70\x65\x5f\x63\x6f\x72\x72\x5f\x64\x69\x6d\x73\x66\x50\
\x4b\x66\x50\x4b\x6c\x69\0\x2e\x6d\x61\x70\x73\0\x6c\x69\x63\x65\x6e\x73\x65\0\
\x74\x68\x72\x65\x61\x64\x68\x69\x73\x74\x2e\x62\x70\x66\x2e\x63\0\x4c\x42\x42\
\x30\x5f\x32\0\x63\x75\x64\x61\x5f\x5f\x72\x65\x74\x70\x72\x6f\x62\x65\0\x63\
\x61\x6c\x6c\x5f\x63\x6f\x75\x6e\x74\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x72\
\x65\x6c\x6b\x72\x65\x74\x70\x72\x6f\x62\x65\x2f\x5f\x5a\x39\x72\x6f\x70\x65\
\x5f\x6e\x6f\x72\x6d\x49\x4c\x62\x31\x45\x4c\x62\x30\x45\x66\x36\x5f\x5f\x68\
\x61\x6c\x66\x45\x76\x50\x4b\x54\x31\x5f\x50\x54\x32\x5f\x69\x69\x69\x69\x69\
\x50\x4b\x69\x66\x66\x66\x31\x34\x72\x6f\x70\x65\x5f\x63\x6f\x72\x72\x5f\x64\
\x69\x6d\x73\x66\x50\x4b\x66\x50\x4b\x6c\x69\0\x2e\x42\x54\x46\0\x2e\x42\x54\
\x46\x2e\x65\x78\x74\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x75\0\
\0\0\x04\0\xf1\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x86\0\0\0\0\0\x03\0\x58\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x8d\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x68\0\0\0\0\0\0\0\x9c\0\0\0\x11\0\x04\0\
\0\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\xa7\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x04\0\
\0\0\0\0\0\0\xb7\x01\0\0\0\0\0\0\x63\x1a\xfc\xff\0\0\0\0\xbf\xa2\0\0\0\0\0\0\
\x07\x02\0\0\xfc\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x85\0\0\0\x01\
\0\0\0\x15\0\x03\0\0\0\0\0\x79\x01\0\0\0\0\0\0\x07\x01\0\0\x01\0\0\0\x7b\x10\0\
\0\0\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x47\x50\x4c\0\0\0\0\0\x20\0\0\0\0\0\0\0\x01\0\
\0\0\x05\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x9c\x01\0\0\x9c\x01\0\0\x0c\x02\
\0\0\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\
\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\xde\x05\0\0\x05\0\0\0\0\0\0\x01\x04\
\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\
\0\x04\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x08\0\0\0\x19\0\0\0\0\0\0\x08\x09\0\0\
\0\x1d\0\0\0\0\0\0\x08\x0a\0\0\0\x23\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\
\0\0\0\0\x02\x0c\0\0\0\x30\0\0\0\0\0\0\x08\x0d\0\0\0\x34\0\0\0\0\0\0\x08\x0e\0\
\0\0\x3a\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\0\x4d\
\0\0\0\x01\0\0\0\0\0\0\0\x52\0\0\0\x05\0\0\0\x40\0\0\0\x5e\0\0\0\x07\0\0\0\x80\
\0\0\0\x62\0\0\0\x0b\0\0\0\xc0\0\0\0\x68\0\0\0\0\0\0\x0e\x0f\0\0\0\x01\0\0\0\0\
\0\0\0\0\0\0\x0d\x02\0\0\0\x73\0\0\0\x01\0\0\x0c\x11\0\0\0\x82\0\0\0\0\0\0\x01\
\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x13\0\0\0\x04\0\0\0\x04\0\0\0\
\x87\0\0\0\0\0\0\x0e\x14\0\0\0\x01\0\0\0\xa8\x01\0\0\x01\0\0\x0f\x20\0\0\0\x10\
\0\0\0\0\0\0\0\x20\0\0\0\xae\x01\0\0\x01\0\0\x0f\x04\0\0\0\x15\0\0\0\0\0\0\0\
\x04\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\
\x54\x59\x50\x45\x5f\x5f\0\x75\x33\x32\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\
\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x75\x36\x34\0\x5f\x5f\x75\x36\x34\0\x75\x6e\
\x73\x69\x67\x6e\x65\x64\x20\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\0\x74\x79\x70\
\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\0\x76\x61\x6c\
\x75\x65\0\x63\x61\x6c\x6c\x5f\x63\x6f\x75\x6e\x74\0\x63\x75\x64\x61\x5f\x5f\
\x72\x65\x74\x70\x72\x6f\x62\x65\0\x63\x68\x61\x72\0\x4c\x49\x43\x45\x4e\x53\
\x45\0\x2f\x68\x6f\x6d\x65\x2f\x79\x75\x6e\x77\x65\x69\x33\x37\x2f\x77\x6f\x72\
\x6b\x73\x70\x61\x63\x65\x2f\x67\x70\x75\x2f\x67\x70\x75\x5f\x65\x78\x74\x2f\
\x77\x6f\x72\x6b\x6c\x6f\x61\x64\x73\x2f\x6c\x6c\x61\x6d\x61\x2e\x63\x70\x70\
\x2f\x6f\x62\x73\x65\x72\x76\x61\x62\x69\x6c\x69\x74\x79\x5f\x6f\x76\x65\x72\
\x68\x65\x61\x64\x2f\x72\x65\x76\x69\x73\x69\x6f\x6e\x2d\x72\x71\x34\x2f\x72\
\x61\x77\x2f\x70\x72\x65\x66\x6c\x69\x67\x68\x74\x2d\x35\x37\x35\x2d\x30\x37\
\x2f\x67\x70\x75\x62\x70\x66\x5f\x74\x6f\x6f\x6c\x5f\x62\x75\x69\x6c\x64\x2f\
\x74\x68\x72\x65\x61\x64\x68\x69\x73\x74\x2f\x74\x68\x72\x65\x61\x64\x68\x69\
\x73\x74\x2e\x62\x70\x66\x2e\x63\0\x69\x6e\x74\x20\x63\x75\x64\x61\x5f\x5f\x72\
\x65\x74\x70\x72\x6f\x62\x65\x28\x29\0\x09\x75\x33\x32\x20\x6b\x65\x79\x20\x3d\
\x20\x30\x3b\0\x09\x75\x36\x34\x20\x2a\x63\x6e\x74\x20\x3d\x20\x62\x70\x66\x5f\
\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\x75\x70\x5f\x65\x6c\x65\x6d\x28\x26\x63\x61\
\x6c\x6c\x5f\x63\x6f\x75\x6e\x74\x2c\x20\x26\x6b\x65\x79\x29\x3b\0\x09\x69\x66\
\x20\x28\x63\x6e\x74\x29\0\x09\x09\x2a\x63\x6e\x74\x20\x2b\x3d\x20\x31\x3b\0\
\x09\x72\x65\x74\x75\x72\x6e\x20\x30\x3b\0\x2e\x6d\x61\x70\x73\0\x6c\x69\x63\
\x65\x6e\x73\x65\0\x6b\x72\x65\x74\x70\x72\x6f\x62\x65\x2f\x5f\x5a\x39\x72\x6f\
\x70\x65\x5f\x6e\x6f\x72\x6d\x49\x4c\x62\x31\x45\x4c\x62\x30\x45\x66\x36\x5f\
\x5f\x68\x61\x6c\x66\x45\x76\x50\x4b\x54\x31\x5f\x50\x54\x32\x5f\x69\x69\x69\
\x69\x69\x50\x4b\x69\x66\x66\x66\x31\x34\x72\x6f\x70\x65\x5f\x63\x6f\x72\x72\
\x5f\x64\x69\x6d\x73\x66\x50\x4b\x66\x50\x4b\x6c\x69\0\x9f\xeb\x01\0\x20\0\0\0\
\0\0\0\0\x14\0\0\0\x14\0\0\0\x6c\0\0\0\x80\0\0\0\0\0\0\0\x08\0\0\0\xb6\x01\0\0\
\x01\0\0\0\0\0\0\0\x12\0\0\0\x10\0\0\0\xb6\x01\0\0\x06\0\0\0\0\0\0\0\x8f\0\0\0\
\x2f\x01\0\0\0\x58\0\0\x08\0\0\0\x8f\0\0\0\x44\x01\0\0\x06\x60\0\0\x20\0\0\0\
\x8f\0\0\0\x52\x01\0\0\x0d\x64\0\0\x38\0\0\0\x8f\0\0\0\x86\x01\0\0\x06\x68\0\0\
\x40\0\0\0\x8f\0\0\0\x90\x01\0\0\x08\x6c\0\0\x58\0\0\0\x8f\0\0\0\x9d\x01\0\0\
\x02\x74\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x03\0\
\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x17\x01\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x09\0\0\0\x02\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x58\x01\0\0\0\0\0\0\xa8\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\
\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\x11\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x67\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x68\
\x02\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x6d\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x88\x02\0\0\0\0\0\
\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xaf\0\0\
\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\x02\0\0\0\0\0\0\x10\0\0\0\0\
\0\0\0\x02\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x09\x01\0\0\x01\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0\x02\0\0\0\0\0\0\xc0\x03\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x0e\x01\0\0\x01\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x60\x06\0\0\0\0\0\0\xa0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct threadhist_bpf *threadhist_bpf::open(const struct bpf_object_open_opts *opts) { return threadhist_bpf__open_opts(opts); }
struct threadhist_bpf *threadhist_bpf::open_and_load() { return threadhist_bpf__open_and_load(); }
int threadhist_bpf::load(struct threadhist_bpf *skel) { return threadhist_bpf__load(skel); }
int threadhist_bpf::attach(struct threadhist_bpf *skel) { return threadhist_bpf__attach(skel); }
void threadhist_bpf::detach(struct threadhist_bpf *skel) { threadhist_bpf__detach(skel); }
void threadhist_bpf::destroy(struct threadhist_bpf *skel) { threadhist_bpf__destroy(skel); }
const void *threadhist_bpf::elf_bytes(size_t *sz) { return threadhist_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
threadhist_bpf__assert(struct threadhist_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __THREADHIST_BPF_SKEL_H__ */
